<?php
return [
    'name' => 'Photos',
    'singular_name' => 'Photo',
    'menu_name' => 'Photo album',
    'name_admin_bar' => 'Photo',
    'all_items' => 'Photos list',
    'add_new' => 'Add photo',
    'add_new_item' => 'Add new photo',
    'edit_item' => 'Edit photo',
    'new_item' => 'New photo',
    'view_item' => 'View photo',
    'search_items' => 'Search photo',
    'not_found' => 'Photos not found',
    'photo_albums' => 'Photoalbums',
    'photo_album' => 'Photoalbum',
    'add_new_album' => 'Add new photoalbum',
    'sort_by_album' => 'Sort by album',
    'photos_count' => 'Photos',
    'of' => 'of',
    'previous'=>'Previous',
    'next' => 'Next',
    'close' => 'Close',
    'albums' => 'Albums',
    'show_more' => 'Show more',
    'added' => 'Added',
];